plugins {
    id 'com.android.library'
}

android {
    namespace 'androidx.media3.decoder.ffmpeg'
    compileSdk 34

    defaultConfig {
        minSdk 21
    }

    externalNativeBuild {
        cmake {
            path 'src/main/jni/CMakeLists.txt'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.annotation:annotation:1.7.0'

    // Fixes 'org.checkerframework.checker.nullness.qual does not exist'
    implementation 'org.checkerframework:checker-qual:3.42.0'

    implementation 'androidx.media3:media3-common:1.6.0'
    implementation 'androidx.media3:media3-decoder:1.6.0'
    implementation 'androidx.media3:media3-exoplayer:1.6.0'
}